version: '3.8'

services:
  mongo:
    image: mongo:8.0.9
    container_name: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    #entrypoint: ["/bin/sh", "/docker-entrypoint-initdb.d/init.js"]
    networks:
      - labnet-upi

volumes:
  mongo_data:

networks:
  labnet-upi:
    external: true
