version: '3.8'

services:
  fastapi:
    build:
      context: .
      target: production  # Ganti ke 'production' untuk image prod
    container_name: fastapi
    env_file:
      - .env.production    # Atau .env.production
    ports:
      - "8000:8000"
    # volumes:
    #   - ./app:/app/app      # Hot reload di dev
    #   - ./scripts:/app/scripts
    networks:
      - labnet-upi
    # depends_on:
    #   - mongo

networks:
  labnet-upi:
    external: true
